import Head from 'next/head';
import '../styles/globals.css';
import 'tailwindcss/tailwind.css';
import { motion } from 'framer-motion';
import Navbar from './api/models/navbar';
import Footer from './api/models/footer';

function MyApp({ Component, pageProps, router }) {
  return (
    <>
      <Head>
        <title>CKG - Chitwan Kagaz Ghar</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css'
          rel='stylesheet'
        />
      </Head>
      <Navbar />
      <motion.div
        key={router.route}
        initial='hidden'
        animate='visible'
        variants={{
          hidden: { opacity: 0, y: -100 },
          visible: { opacity: 1, y: 0 },
        }}
      >
        <Component {...pageProps} />
      </motion.div>
      <Footer />
    </>
  );
}

export default MyApp;
